In [1]:
import pandas as pd 

# đọc file 
df = pd.read_excel("trending_football_players.xlsx")
df

,Player_name,Images,Age,National_team,Positions,Overall,Potential_overall,Current_club,Current_contract,Value,Wage,Total_stats
0,T. Almada,https://cdn.sofifa.net/players/245/371/24_60.png,22,Argentina,"['CAM', 'CM', 'CF']",79,87,Atlanta United,2022 ~ 2025,€39.5M,€10K,2050
1,L. Palma,https://cdn.sofifa.net/player_0.svg,23,Honduras,['LW'],69,75,Celtic,2023 ~ 2028,€2.2M,€22K,1794
2,R. Lavia,https://cdn.sofifa.net/players/263/620/24_60.png,19,Belgium,['CDM'],73,86,Chelsea,2023 ~ 2030,€7M,€32K,1829
3,W. Zaïre-Emery,https://cdn.sofifa.net/players/270/673/24_60.png,17,France,"['CM', 'CDM']",77,89,Paris Saint Germain,2022 ~ 2025,€24M,€9K,2080
4,Gabri Veiga,https://cdn.sofifa.net/players/258/729/24_60.png,21,Spain,"['CM', 'CAM']",78,89,Al Ahli Jeddah,2023 ~ 2026,€31.5M,€28K,1944
...,...,...,...,...,...,...,...,...,...,...,...,...
2995,San Román,https://cdn.sofifa.net/players/242/802/24_60.png,25,Spain,['GK'],68,73,Elche,2023 ~ 2025,€1.4M,€3K,964
2996,D. Afolayan,https://cdn.sofifa.net/players/242/946/24_60.png,25,England,"['LM', 'CF']",70,71,St. Pauli,2023 ~ 2026,€1.9M,€10K,1843
2997,F. Hornby,https://cdn.sofifa.net/players/242/965/24_60.png,23,Scotland,['ST'],69,76,Darmstadt 98,2023 ~ 2027,€2.8M,€11K,1629
2998,Klauss,https://cdn.sofifa.net/players/242/998/24_60.png,26,Brazil,['ST'],74,77,Saint Louis City,2022 ~ 2025,€5.5M,€9K,1808
2999,T. Băluță,https://cdn.sofifa.net/players/243/019/24_60.png,24,Romania,"['CDM', 'CM']",70,74,SSC Farul,2022 ~ 2024,€2.1M,€6K,1782

In [13]:
# Hàm loc và iloc để lọc
"""
    Cú pháp của loc[]:

    df.loc[ <dòng>    ,  <cột>   ]

    Lấy 1 dòng và 1 cột  -> Ô  
       -   df.loc[ 5   ,  "Player name"]

    Lấy nhiều dòng và nhiều cột
       -    df.loc[1:10   ,  ["Player name", "Overall"]]

    Lấy theo điều kiện: Lấy ra dòng có Overall > 80
        -   df.loc[  df["Overall"] > 80   ,   ["Player name", "Overall"]]
"""

'R. Lavia'

In [6]:
result1 = df.loc[ (df["Overall"] >= 85) & (df["National_team"] == "France")  ,
                  ["Player_name", "National_team", "Overall"]] 
result1

      Player_name National_team  Overall
43      K. Mbappé        France       91
94   A. Griezmann        France       88
150    O. Dembélé        France       86
188    O. Dembélé        France       86
283     J. Koundé        France       85
304    M. Maignan        France       87
323  T. Hernández        France       85
329     J. Koundé        France       85
360    K. Benzema        France       90
371      N. Kanté        France       86
379     C. Nkunku        France       86
389     J. Koundé        France       85
430      N. Kanté        France       86
543    K. Benzema        France       90

In [23]:
# câu lệnh điều kiện trong truy vấn 
# In ra thông tin (*) của tất cả các cầu thủ có quốc tịch (National_team) là Portugal

# Cách 1: duyệt từng dòng - kiểm tra ô -> In ra 
for i in range(len(df)):
    team = df.loc[ i  , "National_team" ]  # lấy ra ô có quốc tịch
    if team == "Portugal":
        result = df.loc[i ,  ["Player_name", "Age"]]
        #print(result)


# Cách 2: Biểu thức điều kiện trong loc[], iloc[]
result1 = df.loc[ df["National_team"] == "Portugal"   , ["Player_name", "Age"] ]
#result1

# In ra thông tin của tất cả các cầu thủ có quốc tịch là Brazil và tuổi > 30
check1 = df["National_team"] == "Brazil"
check2 = df["Age"] > 30 
result2 = df.loc[ check1 & check2 , ["Player_name", "Age", "National_team"] ]
result2

             Player_name  Age National_team
39     Cristiano Ronaldo   38      Portugal
50               Rodrygo   22        Brazil
68    Gabriel Martinelli   22        Brazil
70              L. Messi   36     Argentina
73                 Sávio   19        Brazil
...                  ...  ...           ...
2898             Vitinho   23        Brazil
2934     Nicolas Firmino   22        Brazil
2961             Rogério   25        Brazil
2984      23\n D. Valdés   31      Colombia
2998              Klauss   26        Brazil

[418 rows x 3 columns]

In [36]:
# max 
s1 = df["Overall"].max()
print(f"Overall cao nhất: {s1}")

# min 
s2 = df["Overall"].min()
print(f"Overall thấp nhất: {s2}")

# sum 
s3 = df["Overall"].sum()
print(f"Tổng Overall : {s3}")

# count 
s4 = df["Overall"].count()
print(f"Đếm số lượng Overall : {s4}")

# mean <-> average
s5 = df["Overall"].mean()
print(f"Trung bình Overall : {s5}")

"""
    BÀI TẬP THỰC HÀNH:
    1. Hiển thị thông tin cầu thủ có số tuổi cao nhất.
    2. Hiển thị thông tin cầu thủ có Overall cao nhất.
    3. Hiển thị trung bình Overall của các cầu thủ France.
    4. Đếm số lượng cầu thủ có Overall lớn hơn 80 ở Portugal.
"""

Overall cao nhất: 91
Overall thấp nhất: 49
Tổng Overall : 217810
Đếm số lượng Overall : 3000
Trung bình Overall : 72.60333333333334

In [38]:
#1. Hiển thị thông tin cầu thủ có số tuổi cao nhất.
age_max = df["Age"].max()
result1 = df.loc[ df["Age"] == age_max ,  : ]
result1

,Player_name,Images,Age,National_team,Positions,Overall,Potential_overall,Current_club,Current_contract,Value,Wage,Total_stats
540,23\n G. Buffon,https://cdn.sofifa.net/players/001/179/23_60.png,44,Italy,['GK'],77,77,Parma,2021 ~ 2024,€1.2M,€3K,1244
660,23\n G. Buffon,https://cdn.sofifa.net/players/001/179/23_60.png,44,Italy,['GK'],77,77,Parma,2021 ~ 2024,€1.2M,€3K,1244
1261,23\n G. Buffon,https://cdn.sofifa.net/players/001/179/23_60.png,44,Italy,['GK'],77,77,Parma,2021 ~ 2024,€1.2M,€3K,1244

In [39]:
 #   2. Hiển thị thông tin cầu thủ có Overall cao nhất.
overall_max = df["Overall"].max()
result2 = df.loc[ df["Overall"] == overall_max , : ]
result2

,Player_name,Images,Age,National_team,Positions,Overall,Potential_overall,Current_club,Current_contract,Value,Wage,Total_stats
41,E. Haaland,https://cdn.sofifa.net/players/239/085/24_60.png,22,Norway,['ST'],91,94,Manchester City,2022 ~ 2027,€185M,€340K,2158
43,K. Mbappé,https://cdn.sofifa.net/players/231/747/24_60.png,24,France,"['ST', 'LW']",91,94,Paris Saint Germain,2018 ~ 2024,€181.5M,€230K,2204
200,K. De Bruyne,https://cdn.sofifa.net/players/192/985/24_60.png,32,Belgium,"['CM', 'CAM']",91,91,Manchester City,2015 ~ 2025,€103M,€350K,2317

In [42]:
#3. Hiển thị trung bình Overall của các cầu thủ France.
result3 = df.loc[ df["National_team"] == "France"   , : ]
avg_overall = result3["Overall"].mean()
print(f"Trung bình Overall cầu thủ Pháp: {avg_overall:.4f}")

Trung bình Overall cầu thủ Pháp: 73.9264

In [45]:
# 4. Đếm số lượng cầu thủ có Overall lớn hơn 80 ở Portugal.
df_tmp = df.loc[ df["National_team"] == "Portugal"   , : ]
result4 = df_tmp.loc[ df_tmp["Overall"] > 80  ,  : ]

# Cách 1: Sử dụng hàm len()
print(f"Số lượng cầu thủ có Overall > 80 tại Portugal: {len(result4)}")

# Cách 2: Sử dụng hàm count()
countx = result4["Player_name"].count()
print(f"Số lượng cầu thủ có Overall > 80 tại Portugal: {countx}")

Số lượng cầu thủ có Overall > 80 tại Portugal: 23
Số lượng cầu thủ có Overall > 80 tại Portugal: 23

In [48]:
# Dùng value_counts để đếm có bao nhiêu cầu thủ thuộc các quốc gia
len(df["Age"].value_counts())

26

In [ ]:
import numpy as np 

def sigmoid(s):   
    return 1/(1 + np.exp(-s))

def logistic_sigmoid_regression(X, y, w_init, eta, tol = 1e-4, max_count = 10000):
    w = [w_init]    
    it = 0
    N = X.shape[1]
    d = X.shape[0]
    count = 0
    check_w_after = 20
    while count < max_count:
        # mix data 
        mix_id = np.random.permutation(N)
        for i in mix_id:
            xi = X[:, i].reshape(d, 1)
            yi = y[i]
            zi = sigmoid(np.dot(w[-1].T, xi))
            w_new = w[-1] + eta*(yi - zi)*xi
            count += 1
            # stopping criteria
            if count%check_w_after == 0:                
                if np.linalg.norm(w_new - w[-check_w_after]) < tol:
                    return w
            w.append(w_new)
    return w
eta = .05 
d = X.shape[0]
w_init = np.random.randn(d, 1)

w = logistic_sigmoid_regression(X, y, w_init, eta)
print(w[-1])